/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

	import java.awt.Color;
	import java.sql.Connection;
        import java.sql.ResultSet;
	import javax.swing.JOptionPane;
        import pbo_manajemen_toko.Login.Session;


/**
 *
 * @author nabil
 */
public class DashboardKasir extends javax.swing.JFrame {

    /**
     * Creates new form DashboardKasir
     */
    public DashboardKasir() {
        initComponents();
        //auto fullscreen
        setExtendedState(DashboardKasir.MAXIMIZED_BOTH);
        //bg warna putih
        getContentPane().setBackground(new Color(250, 250, 250));
        loadDashboard();
        loadnama();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashbaordBtn = new javax.swing.JLabel();
        dashbaordBtnIcon = new javax.swing.JLabel();
        listBarangBtn = new javax.swing.JLabel();
        listBarangBtnIcon = new javax.swing.JLabel();
        transaksiBtn = new javax.swing.JLabel();
        transaksiBtnIcon = new javax.swing.JLabel();
        returnBarangBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        logoutBtnIcon = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        userRoleLabel = new javax.swing.JLabel();
        historiTransaksiBtn = new javax.swing.JLabel();
        historiTransaksiBtnIcon = new javax.swing.JLabel();
        listBarangIcon = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        totalPendapatanPanel = new javax.swing.JPanel();
        totalPendapatanLabel = new javax.swing.JLabel();
        pendapatanIcon = new javax.swing.JLabel();
        fpendapatan = new javax.swing.JLabel();
        totalTransaksiPanel = new javax.swing.JPanel();
        totalTransaksiLabel = new javax.swing.JLabel();
        totalTransaksiIcon = new javax.swing.JLabel();
        ftotaltsc = new javax.swing.JLabel();
        totalBarangTerjualPanel = new javax.swing.JPanel();
        totalBarangTerjualLabel = new javax.swing.JLabel();
        totalBarangTerjualIcon = new javax.swing.JLabel();
        fbrgjual = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Kasir");
        setBackground(new java.awt.Color(250, 250, 250));

        sideBar.setBackground(new java.awt.Color(237, 255, 249));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 142, 110));
        jLabel2.setText("TokoAja.");

        dashbaordBtn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        dashbaordBtn.setForeground(new java.awt.Color(50, 142, 110));
        dashbaordBtn.setText("Dashboard");
        dashbaordBtn.setToolTipText("");
        dashbaordBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dashbaordBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame-1.png"))); // NOI18N

        listBarangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        listBarangBtn.setForeground(new java.awt.Color(123, 122, 120));
        listBarangBtn.setText("List Barang");
        listBarangBtn.setToolTipText("");
        listBarangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        listBarangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBarangBtnMouseClicked(evt);
            }
        });

        listBarangBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box-1.png"))); // NOI18N

        transaksiBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        transaksiBtn.setForeground(new java.awt.Color(123, 122, 120));
        transaksiBtn.setText("Transaksi");
        transaksiBtn.setToolTipText("");
        transaksiBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        transaksiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiBtnMouseClicked(evt);
            }
        });

        transaksiBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/transaction.png"))); // NOI18N

        returnBarangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        returnBarangBtn.setForeground(new java.awt.Color(123, 122, 120));
        returnBarangBtn.setText("Return Barang");
        returnBarangBtn.setToolTipText("");
        returnBarangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        returnBarangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBarangBtnMouseClicked(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(123, 122, 120));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        logoutBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/logout.png"))); // NOI18N
        logoutBtnIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnIconMouseClicked(evt);
            }
        });

        userNameLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        userNameLabel.setText("Nabila");
        userNameLabel.setToolTipText("");
        userNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/profile-img.png"))); // NOI18N
        profileIcon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                profileIconPropertyChange(evt);
            }
        });

        userRoleLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        userRoleLabel.setForeground(new java.awt.Color(123, 122, 120));
        userRoleLabel.setText("Kasir");
        userRoleLabel.setToolTipText("");
        userRoleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        historiTransaksiBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        historiTransaksiBtn.setForeground(new java.awt.Color(123, 122, 120));
        historiTransaksiBtn.setText("Histori Transaksi");
        historiTransaksiBtn.setToolTipText("");
        historiTransaksiBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        historiTransaksiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historiTransaksiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historiTransaksiBtnMouseClicked(evt);
            }
        });

        historiTransaksiBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/transaction-history-stroke-rounded 1.png"))); // NOI18N

        listBarangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/product-management.png"))); // NOI18N

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(dashbaordBtnIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dashbaordBtn))
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(listBarangBtnIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listBarangBtn))
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(transaksiBtnIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transaksiBtn))
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(historiTransaksiBtnIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(historiTransaksiBtn))
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(profileIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameLabel)
                                    .addComponent(userRoleLabel)))
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(logoutBtnIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logoutBtn))))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(listBarangIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnBarangBtn)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashbaordBtn)
                    .addComponent(dashbaordBtnIcon))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listBarangBtn)
                    .addComponent(listBarangBtnIcon))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transaksiBtn)
                    .addComponent(transaksiBtnIcon))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(returnBarangBtn)
                    .addComponent(listBarangIcon))
                .addGap(27, 27, 27)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historiTransaksiBtn)
                    .addComponent(historiTransaksiBtnIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userRoleLabel))
                    .addComponent(profileIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn)
                    .addComponent(logoutBtnIcon))
                .addGap(41, 41, 41))
        );

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dashbaordBtn, dashbaordBtnIcon});

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {listBarangBtn, listBarangBtnIcon});

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {transaksiBtn, transaksiBtnIcon});

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {historiTransaksiBtn, historiTransaksiBtnIcon, returnBarangBtn});

        tittle.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        tittle.setForeground(new java.awt.Color(50, 142, 110));
        tittle.setText("Dashboard");

        totalPendapatanPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalPendapatanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        totalPendapatanLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalPendapatanLabel.setText("Total Pendapatan");
        totalPendapatanLabel.setToolTipText("");
        totalPendapatanLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        pendapatanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/money-recive.png"))); // NOI18N

        fpendapatan.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        fpendapatan.setText("Rp. 0");
        fpendapatan.setToolTipText("");
        fpendapatan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout totalPendapatanPanelLayout = new javax.swing.GroupLayout(totalPendapatanPanel);
        totalPendapatanPanel.setLayout(totalPendapatanPanelLayout);
        totalPendapatanPanelLayout.setHorizontalGroup(
            totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalPendapatanPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalPendapatanPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fpendapatan))
                    .addGroup(totalPendapatanPanelLayout.createSequentialGroup()
                        .addComponent(pendapatanIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPendapatanLabel)))
                .addGap(19, 19, 19))
        );
        totalPendapatanPanelLayout.setVerticalGroup(
            totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalPendapatanLabel)
                    .addComponent(pendapatanIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fpendapatan)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalTransaksiPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalTransaksiPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        totalTransaksiLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalTransaksiLabel.setText("Total Transaksi");
        totalTransaksiLabel.setToolTipText("");
        totalTransaksiLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        totalTransaksiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box.png"))); // NOI18N

        ftotaltsc.setBackground(new java.awt.Color(255, 255, 255));
        ftotaltsc.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        ftotaltsc.setText("0");
        ftotaltsc.setToolTipText("");
        ftotaltsc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout totalTransaksiPanelLayout = new javax.swing.GroupLayout(totalTransaksiPanel);
        totalTransaksiPanel.setLayout(totalTransaksiPanelLayout);
        totalTransaksiPanelLayout.setHorizontalGroup(
            totalTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTransaksiPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(totalTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalTransaksiPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ftotaltsc))
                    .addGroup(totalTransaksiPanelLayout.createSequentialGroup()
                        .addComponent(totalTransaksiIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalTransaksiLabel)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        totalTransaksiPanelLayout.setVerticalGroup(
            totalTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTransaksiPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(totalTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalTransaksiLabel)
                    .addComponent(totalTransaksiIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftotaltsc)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalBarangTerjualPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalBarangTerjualPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        totalBarangTerjualLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalBarangTerjualLabel.setText("Total Barang Terjual");
        totalBarangTerjualLabel.setToolTipText("");
        totalBarangTerjualLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        totalBarangTerjualIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box.png"))); // NOI18N

        fbrgjual.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        fbrgjual.setText("0");
        fbrgjual.setToolTipText("");
        fbrgjual.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout totalBarangTerjualPanelLayout = new javax.swing.GroupLayout(totalBarangTerjualPanel);
        totalBarangTerjualPanel.setLayout(totalBarangTerjualPanelLayout);
        totalBarangTerjualPanelLayout.setHorizontalGroup(
            totalBarangTerjualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBarangTerjualPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(totalBarangTerjualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalBarangTerjualPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fbrgjual))
                    .addGroup(totalBarangTerjualPanelLayout.createSequentialGroup()
                        .addComponent(totalBarangTerjualIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBarangTerjualLabel)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        totalBarangTerjualPanelLayout.setVerticalGroup(
            totalBarangTerjualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBarangTerjualPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(totalBarangTerjualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalBarangTerjualLabel)
                    .addComponent(totalBarangTerjualIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fbrgjual)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalPendapatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(totalTransaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(totalBarangTerjualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPendapatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTransaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBarangTerjualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnIconMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        Login.Session.clearSession();
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    // Method untuk tombol List Barang
private void listBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {
    ListBarang lstB = new ListBarang();
    lstB.setVisible(true);
    dispose();
}

// Method untuk tombol Transaksi
private void transaksiBtnMouseClicked(java.awt.event.MouseEvent evt) {
    int idUser = Session.getUserId(); // Anda mungkin perlu menyesuaikan ini
    TransaksiKasir transaksi = new TransaksiKasir(idUser);
    transaksi.setVisible(true);
    dispose();
}

// Method untuk tombol Return Barang
private void returnBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {
    ReturnBarang rtrB = new ReturnBarang();
    rtrB.setVisible(true);
    dispose();
}

// Method untuk tombol Histori Transaksi
private void historiTransaksiBtnMouseClicked(java.awt.event.MouseEvent evt) {
    HistoriKasir hst = new HistoriKasir();
    hst.setVisible(true);
    dispose();
}

// Jangan hapus method ini, ini sudah benar
private void profileIconPropertyChange(java.beans.PropertyChangeEvent evt) {                                             
    // TODO add your handling code here:
}
    
    private void loadDashboard() {
        try (java.sql.Connection Vconn = Koneksi.konfigDB()) {
            
            // Total Pendapatan
            String sqlPendapatan = "SELECT SUM(total_harga) AS total_pendapatan FROM transactions";
            java.sql.PreparedStatement ps1 = Vconn.prepareStatement(sqlPendapatan);
            java.sql.ResultSet rs1 = ps1.executeQuery();
            if (rs1.next()) {
                double totalPendapatan = rs1.getDouble("total_pendapatan");
                fpendapatan.setText("Rp. "+ totalPendapatan);
            }
            
            // Total Transaksi
            String sqlTransaksi = "SELECT COUNT(*) AS total_transaksi FROM transactions";
            java.sql.PreparedStatement ps2 = Vconn.prepareStatement(sqlTransaksi);
            java.sql.ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                ftotaltsc.setText(rs2.getString("total_transaksi"));
            }
            
            // Total Barang Terjual
            String sqlBarang = "SELECT COALESCE(SUM(jumlah), 0) AS total_barang FROM transaction_items";
            java.sql.PreparedStatement ps3 = Vconn.prepareStatement(sqlBarang);
            java.sql.ResultSet rs3 = ps3.executeQuery();
            if (rs3.next()) {
                fbrgjual.setText(rs3.getString("total_barang"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load dashboard: "+ e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardKasir().setVisible(true);
            }
        });
    }
    
                private void loadnama() {
                int idUser = Login.Session.getUserId();
                String nama = "";
                try {
                    java.sql.Connection Vconn = (Connection)Koneksi.konfigDB();
                    String sql = "SELECT nama FROM users WHERE id_user = ?";
                    java.sql.PreparedStatement s = Vconn.prepareStatement(sql);
                    s.setInt(1, idUser);
                    ResultSet rs = s.executeQuery();

                    if (rs.next()) {
                        nama = rs.getString("nama");
                    }

                    rs.close();
                    s.close();
                    Vconn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                userNameLabel.setText(""+nama+"");
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashbaordBtn;
    private javax.swing.JLabel dashbaordBtnIcon;
    private javax.swing.JLabel fbrgjual;
    private javax.swing.JLabel fpendapatan;
    private javax.swing.JLabel ftotaltsc;
    private javax.swing.JLabel historiTransaksiBtn;
    private javax.swing.JLabel historiTransaksiBtnIcon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel listBarangBtn;
    private javax.swing.JLabel listBarangBtnIcon;
    private javax.swing.JLabel listBarangIcon;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel logoutBtnIcon;
    private javax.swing.JLabel pendapatanIcon;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel returnBarangBtn;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel totalBarangTerjualIcon;
    private javax.swing.JLabel totalBarangTerjualLabel;
    private javax.swing.JPanel totalBarangTerjualPanel;
    private javax.swing.JLabel totalPendapatanLabel;
    private javax.swing.JPanel totalPendapatanPanel;
    private javax.swing.JLabel totalTransaksiIcon;
    private javax.swing.JLabel totalTransaksiLabel;
    private javax.swing.JPanel totalTransaksiPanel;
    private javax.swing.JLabel transaksiBtn;
    private javax.swing.JLabel transaksiBtnIcon;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userRoleLabel;
    // End of variables declaration//GEN-END:variables
}
