/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nabil
 */
public class HistoriKasir extends javax.swing.JFrame {

    /**
     * Creates new form HistoriKasir
     */
    public HistoriKasir() {
        initComponents();
        // Set background color for the content pane to match the overall light theme
        getContentPane().setBackground(new Color(250, 250, 250));
//        loadHistoriTransaksi(null);
        
        
        setFullScreenMode(true);
        tampil_tabel_histori_transaksi();
        loadnama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        logoTitleLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        transaksiBtn = new javax.swing.JLabel();
        historiTransaksiBtn = new javax.swing.JLabel();
        returnBarangBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        profileNameLabel = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        profileRoleLabel = new javax.swing.JLabel();
        listBarangBtn = new javax.swing.JLabel();
        listBarangIcon = new javax.swing.JLabel();
        returnBarangBtnIcon = new javax.swing.JLabel();
        transaksiBtnIcon = new javax.swing.JLabel();
        listBarangBtnIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        mainTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftblhistori = new javax.swing.JTable();
        fbtnhst = new javax.swing.JButton();
        fresethst = new javax.swing.JButton();
        fcarihst = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Histori Transaksi");
        setBackground(new java.awt.Color(250, 250, 250));

        sideBarPanel.setBackground(new java.awt.Color(237, 255, 249));
        sideBarPanel.setForeground(new java.awt.Color(237, 255, 249));

        logoTitleLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        logoTitleLabel1.setForeground(new java.awt.Color(50, 142, 110));
        logoTitleLabel1.setText("TokoAja.");

        dashboardBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(123, 122, 120));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setToolTipText("");
        dashboardBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });

        transaksiBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        transaksiBtn.setForeground(new java.awt.Color(123, 122, 120));
        transaksiBtn.setText("Transaksi");
        transaksiBtn.setToolTipText("");
        transaksiBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        transaksiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiBtnMouseClicked(evt);
            }
        });

        historiTransaksiBtn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        historiTransaksiBtn.setForeground(new java.awt.Color(50, 142, 110));
        historiTransaksiBtn.setText("Histori Transaksi");
        historiTransaksiBtn.setToolTipText("");
        historiTransaksiBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        returnBarangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        returnBarangBtn.setForeground(new java.awt.Color(123, 122, 120));
        returnBarangBtn.setText("Return Barang");
        returnBarangBtn.setToolTipText("");
        returnBarangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        returnBarangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBarangBtnMouseClicked(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(123, 122, 120));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/logout.png"))); // NOI18N

        profileNameLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        profileNameLabel.setText("Nabila");
        profileNameLabel.setToolTipText("");
        profileNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/profile-img.png"))); // NOI18N

        profileRoleLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        profileRoleLabel.setForeground(new java.awt.Color(123, 122, 120));
        profileRoleLabel.setText("Kasir");
        profileRoleLabel.setToolTipText("");
        profileRoleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        listBarangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        listBarangBtn.setForeground(new java.awt.Color(123, 122, 120));
        listBarangBtn.setText("List Barang");
        listBarangBtn.setToolTipText("");
        listBarangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        listBarangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBarangBtnMouseClicked(evt);
            }
        });

        listBarangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/product-management.png"))); // NOI18N

        returnBarangBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/transaction-history-stroke-rounded 1.png"))); // NOI18N

        transaksiBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/transaction.png"))); // NOI18N

        listBarangBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box-1.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame.png"))); // NOI18N

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoTitleLabel1)
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addComponent(profileIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(profileNameLabel)
                                    .addComponent(profileRoleLabel)))
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addComponent(logoutIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logoutBtn))
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(listBarangBtnIcon))
                                .addGap(12, 12, 12)
                                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listBarangBtn)
                                    .addComponent(dashboardBtn)))
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addComponent(transaksiBtnIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(transaksiBtn))
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addComponent(listBarangIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(returnBarangBtn))))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(returnBarangBtnIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(historiTransaksiBtn)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoTitleLabel1)
                .addGap(24, 24, 24)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(dashboardBtn))
                        .addGap(26, 26, 26)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listBarangBtn)
                            .addComponent(listBarangBtnIcon))
                        .addGap(26, 26, 26)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transaksiBtn)
                            .addComponent(transaksiBtnIcon))
                        .addGap(26, 26, 26)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listBarangIcon)
                            .addComponent(returnBarangBtn))
                        .addGap(33, 33, 33)
                        .addComponent(returnBarangBtnIcon))
                    .addComponent(historiTransaksiBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileIcon)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(profileNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileRoleLabel)))
                .addGap(28, 28, 28)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn)
                    .addComponent(logoutIcon))
                .addGap(41, 41, 41))
        );

        sideBarPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {listBarangBtn, listBarangIcon});

        sideBarPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logoutBtn, logoutIcon});

        mainContentPanel.setBackground(new java.awt.Color(250, 250, 250));
        mainContentPanel.setLayout(null);

        mainTitleLabel.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        mainTitleLabel.setForeground(new java.awt.Color(50, 142, 110));
        mainTitleLabel.setText("Histori Transaksi");
        mainContentPanel.add(mainTitleLabel);
        mainTitleLabel.setBounds(34, 34, 250, 34);

        ftblhistori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "ID User", "ID Diskon", "Total Harga", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(ftblhistori);

        mainContentPanel.add(jScrollPane1);
        jScrollPane1.setBounds(34, 150, 850, 400);

        fbtnhst.setBackground(new java.awt.Color(50, 142, 110));
        fbtnhst.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        fbtnhst.setForeground(new java.awt.Color(255, 255, 255));
        fbtnhst.setText("Cari");
        fbtnhst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtnhstActionPerformed(evt);
            }
        });
        mainContentPanel.add(fbtnhst);
        fbtnhst.setBounds(300, 100, 100, 35);

        fresethst.setBackground(new java.awt.Color(50, 142, 110));
        fresethst.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        fresethst.setForeground(new java.awt.Color(255, 255, 255));
        fresethst.setText("Reset");
        fresethst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresethstActionPerformed(evt);
            }
        });
        mainContentPanel.add(fresethst);
        fresethst.setBounds(410, 100, 100, 35);

        fcarihst.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        mainContentPanel.add(fcarihst);
        fcarihst.setBounds(34, 100, 250, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
 * Method untuk toggle fullscreen mode
 * @param fullscreen true untuk fullscreen, false untuk windowed
 */
private void setFullScreenMode(boolean fullscreen) {
    if (fullscreen) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    } else {
        setExtendedState(JFrame.NORMAL);
        setLocationRelativeTo(null); // Center the window
    }
}

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        DashboardKasir dsb = new DashboardKasir();
        dsb.setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void transaksiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiBtnMouseClicked
        int idUser = Login.Session.getUserId();;
        TransaksiKasir transaksi = new TransaksiKasir(idUser);
        transaksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_transaksiBtnMouseClicked

    private void returnBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBarangBtnMouseClicked
        ReturnBarang rtrB = new ReturnBarang();
        rtrB.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBarangBtnMouseClicked

    private void listBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBarangBtnMouseClicked
        ListBarang lstB = new ListBarang();
        lstB.setVisible(true);
        dispose();
    }//GEN-LAST:event_listBarangBtnMouseClicked

    private void fbtnhstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtnhstActionPerformed
        String keyword = fcarihst.getText();
        cariData(keyword);
    }//GEN-LAST:event_fbtnhstActionPerformed

    private void fresethstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresethstActionPerformed
        fcarihst.setText("");
        tampil_tabel_histori_transaksi();
    }//GEN-LAST:event_fresethstActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {
        Login.Session.clearSession();
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }
    
    private void tampil_tabel_histori_transaksi() {
        // membuat objek model pada tabel
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("ID Transaksi");
        tb.addColumn("ID User");
        tb.addColumn("ID Diskon");
        tb.addColumn("Total Harga");
        tb.addColumn("Tanggal");
        
        try {
            // 1. Query
            String query = "SELECT * FROM transactions";
            
            // 2. Fungsi Koneksi
            java.sql.Connection Vconn = (Connection)Koneksi.konfigDB();
            
            // 3. Kirim parameter fungsi java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
            // 4. Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            // 5. Looping
            while (r.next()) {
                tb.addRow(new Object[] {
                r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5)
                });
            }
            ftblhistori.setModel(tb);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencari: "+e.getMessage());
        }
        
    }
    
    public void cariData(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("ID User");
        model.addColumn("ID Diskon");
        model.addColumn("Total Harga");
        model.addColumn("Tanggal");
        
        try {
            String query = "SELECT * FROM transactions WHERE id_transaksi LIKE ? or id_user LIKE ? ";
            java.sql.Connection Vconn = (Connection)Koneksi.konfigDB();
            java.sql.PreparedStatement s = Vconn.prepareStatement(query);
            s.setString(1, "%"+keyword+"%");
            s.setString(2, "%"+keyword+"%");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                model.addRow(new Object[] {
                    r.getString("id_transaksi"),
                    r.getString("id_user"),
                    r.getString("id_diskon"),
                    r.getString("total_harga"),
                    r.getString("tanggal"),
                });
            }
            
            ftblhistori.setModel(model);
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencari: "+e.getMessage());
        }
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriKasir().setVisible(true);
            }
        });
    }
    
    private void loadnama() {
                int idUser = Login.Session.getUserId();
                String nama = "";
                try {
                    java.sql.Connection Vconn = (Connection)Koneksi.konfigDB();
                    String sql = "SELECT nama FROM users WHERE id_user = ?";
                    java.sql.PreparedStatement s = Vconn.prepareStatement(sql);
                    s.setInt(1, idUser);
                    ResultSet rs = s.executeQuery();

                    if (rs.next()) {
                        nama = rs.getString("nama");
                    }

                    rs.close();
                    s.close();
                    Vconn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                profileNameLabel.setText(""+nama+"");
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JButton fbtnhst;
    private javax.swing.JTextField fcarihst;
    private javax.swing.JButton fresethst;
    private javax.swing.JTable ftblhistori;
    private javax.swing.JLabel historiTransaksiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listBarangBtn;
    private javax.swing.JLabel listBarangBtnIcon;
    private javax.swing.JLabel listBarangIcon;
    private javax.swing.JLabel logoTitleLabel1;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JLabel profileRoleLabel;
    private javax.swing.JLabel returnBarangBtn;
    private javax.swing.JLabel returnBarangBtnIcon;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel transaksiBtn;
    private javax.swing.JLabel transaksiBtnIcon;
    // End of variables declaration//GEN-END:variables
}

