/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nabil
 */
public class ReturnBarang extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBarang
     */
    public ReturnBarang() {
        initComponents();
        // Set background color for the content pane to match the overall light theme
        getContentPane().setBackground(new Color(250, 250, 250));
        loadReturnTable();
        
        setFullScreenMode(true);
        loadnama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        logoTitleLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        transaksiBtn = new javax.swing.JLabel();
        historiTransaksiBtn = new javax.swing.JLabel();
        returnBarangBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        profileNameLabel = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        profileRoleLabel = new javax.swing.JLabel();
        listBarangBtn = new javax.swing.JLabel();
        returnBarangBtnIcon = new javax.swing.JLabel();
        transaksiBtnIcon = new javax.swing.JLabel();
        listBarangBtnIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        returnBarangIcon = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        mainTitleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        finputidtsc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        finputtgl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftbldetailtsc = new javax.swing.JTable();
        fbtnsvreturn = new javax.swing.JButton();
        fbtnbatal = new javax.swing.JButton();
        fbtncek = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fjumlahretur = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ftblreturn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Return Barang");
        setBackground(new java.awt.Color(250, 250, 250));

        sideBarPanel.setBackground(new java.awt.Color(237, 255, 249));
        sideBarPanel.setForeground(new java.awt.Color(237, 255, 249));

        logoTitleLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        logoTitleLabel1.setForeground(new java.awt.Color(50, 142, 110));
        logoTitleLabel1.setText("TokoAja.");

        dashboardBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(123, 122, 120));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setToolTipText("");
        dashboardBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });

        transaksiBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        transaksiBtn.setForeground(new java.awt.Color(123, 122, 120));
        transaksiBtn.setText("Transaksi");
        transaksiBtn.setToolTipText("");
        transaksiBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        transaksiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiBtnMouseClicked(evt);
            }
        });

        historiTransaksiBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        historiTransaksiBtn.setForeground(new java.awt.Color(123, 122, 120));
        historiTransaksiBtn.setText("Histori Transaksi");
        historiTransaksiBtn.setToolTipText("");
        historiTransaksiBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        historiTransaksiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historiTransaksiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historiTransaksiBtnMouseClicked(evt);
            }
        });

        returnBarangBtn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        returnBarangBtn.setForeground(new java.awt.Color(50, 142, 110));
        returnBarangBtn.setText("Return Barang");
        returnBarangBtn.setToolTipText("");
        returnBarangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        logoutBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(123, 122, 120));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        profileNameLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        profileNameLabel.setText("Nabila");
        profileNameLabel.setToolTipText("");
        profileNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/profile-img.png"))); // NOI18N

        profileRoleLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        profileRoleLabel.setForeground(new java.awt.Color(123, 122, 120));
        profileRoleLabel.setText("Kasir");
        profileRoleLabel.setToolTipText("");
        profileRoleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        listBarangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        listBarangBtn.setForeground(new java.awt.Color(123, 122, 120));
        listBarangBtn.setText("List Barang");
        listBarangBtn.setToolTipText("");
        listBarangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        listBarangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBarangBtnMouseClicked(evt);
            }
        });

        returnBarangBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/transaction-history-stroke-rounded 1.png"))); // NOI18N

        transaksiBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/transaction.png"))); // NOI18N

        listBarangBtnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box-1.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame.png"))); // NOI18N

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/logout.png"))); // NOI18N

        returnBarangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/product-management.png"))); // NOI18N

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoTitleLabel1)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(profileIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileNameLabel)
                            .addComponent(profileRoleLabel)))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(logoutIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(returnBarangBtnIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(historiTransaksiBtn))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashboardBtn))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(listBarangBtnIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listBarangBtn))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(transaksiBtnIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transaksiBtn))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(returnBarangIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returnBarangBtn)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoTitleLabel1)
                .addGap(24, 24, 24)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dashboardBtn))
                .addGap(26, 26, 26)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listBarangBtn)
                    .addComponent(listBarangBtnIcon))
                .addGap(26, 26, 26)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transaksiBtn)
                    .addComponent(transaksiBtnIcon))
                .addGap(26, 26, 26)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(returnBarangIcon)
                    .addComponent(returnBarangBtn))
                .addGap(26, 26, 26)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(returnBarangBtnIcon)
                    .addComponent(historiTransaksiBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileIcon)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(profileNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileRoleLabel)))
                .addGap(28, 28, 28)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn)
                    .addComponent(logoutIcon))
                .addGap(41, 41, 41))
        );

        mainContentPanel.setBackground(new java.awt.Color(250, 250, 250));
        mainContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitleLabel.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        mainTitleLabel.setForeground(new java.awt.Color(50, 142, 110));
        mainTitleLabel.setText("Return Barang");
        mainContentPanel.add(mainTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 34, 250, 34));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel12.setText("ID Transaksi");

        finputidtsc.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal");

        finputtgl.setEditable(false);
        finputtgl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        finputtgl.setEnabled(false);

        ftbldetailtsc.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ftbldetailtsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Item", "Jumlah", "Total"
            }
        ));
        ftbldetailtsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftbldetailtscMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ftbldetailtsc);

        fbtnsvreturn.setBackground(new java.awt.Color(204, 0, 0));
        fbtnsvreturn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        fbtnsvreturn.setForeground(new java.awt.Color(255, 255, 255));
        fbtnsvreturn.setText("Simpan Return");
        fbtnsvreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtnsvreturnActionPerformed(evt);
            }
        });

        fbtnbatal.setBackground(new java.awt.Color(50, 142, 110));
        fbtnbatal.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        fbtnbatal.setForeground(new java.awt.Color(255, 255, 255));
        fbtnbatal.setText("Batal");
        fbtnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtnbatalActionPerformed(evt);
            }
        });

        fbtncek.setBackground(new java.awt.Color(50, 142, 110));
        fbtncek.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        fbtncek.setForeground(new java.awt.Color(255, 255, 255));
        fbtncek.setText("Cek Transaksi");
        fbtncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtncekActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel11.setText("Jumlah Return");

        fjumlahretur.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fbtncek))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(finputidtsc)
                                    .addComponent(finputtgl, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fjumlahretur, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fbtnsvreturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fbtnbatal)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(finputidtsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finputtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(fbtncek)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fjumlahretur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fbtnbatal)
                    .addComponent(fbtnsvreturn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainContentPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 90, 466, 480));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(50, 142, 110));
        jLabel15.setText("Data Return");

        ftblreturn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ftblreturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Return", "ID Transaksi", "ID Item", "Jumlah Return", "Tanggal Return"
            }
        ));
        jScrollPane2.setViewportView(ftblreturn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addContainerGap(338, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainContentPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 450, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method untuk toggle fullscreen mode
     * @param fullscreen true untuk fullscreen, false untuk windowed
     */
    private void setFullScreenMode(boolean fullscreen) {
        if (fullscreen) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        } else {
            setExtendedState(JFrame.NORMAL);
            setLocationRelativeTo(null); // Center the window
        }
    }

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        DashboardKasir dsb = new DashboardKasir();
        dsb.setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void transaksiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiBtnMouseClicked
        int idUser = Login.Session.getUserId();;
        TransaksiKasir transaksi = new TransaksiKasir(idUser);
        transaksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_transaksiBtnMouseClicked

    private void historiTransaksiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historiTransaksiBtnMouseClicked
        HistoriKasir hst = new HistoriKasir();
        hst.setVisible(true);
        dispose();
    }//GEN-LAST:event_historiTransaksiBtnMouseClicked

       private void listBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBarangBtnMouseClicked
        ListBarang lstB = new ListBarang();
        lstB.setVisible(true);
        dispose();
    }//GEN-LAST:event_listBarangBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        Login.Session.clearSession();
        System.exit(0);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void fbtncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtncekActionPerformed
        String id = finputidtsc.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID Transaksi terlebih dahulu");
            return;
        }
        loadBarangTransaksi(id);
    }//GEN-LAST:event_fbtncekActionPerformed

    private void ftbldetailtscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftbldetailtscMouseClicked
        int row = ftbldetailtsc.getSelectedRow();
        if (row != -1) {
            
        }
    }//GEN-LAST:event_ftbldetailtscMouseClicked

    private void fbtnsvreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtnsvreturnActionPerformed
        SaveReturn();
    }//GEN-LAST:event_fbtnsvreturnActionPerformed

    private void fbtnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtnbatalActionPerformed
        finputidtsc.setText("");
        finputtgl.setText("");
        fjumlahretur.setText("");
        ((DefaultTableModel) ftbldetailtsc.getModel()).setRowCount(0);
    }//GEN-LAST:event_fbtnbatalActionPerformed
    
    private void loadBarangTransaksi(String idTransaksi) {
        DefaultTableModel tblModel = (DefaultTableModel) ftbldetailtsc.getModel();
        tblModel.setRowCount(0);
        
        try(java.sql.Connection Vconn = Koneksi.konfigDB()) {
            String query = "SELECT id_item, jumlah, subtotal AS total " + "FROM transaction_items WHERE id_transaksi = ?";
            java.sql.PreparedStatement ps = Vconn.prepareStatement(query);
            ps.setString(1, idTransaksi);
            java.sql.ResultSet rs = ps.executeQuery();
            
            tblModel.setRowCount(0);
            
            while (rs.next()) {
                tblModel.addRow(new Object[] {
                    rs.getString("id_item"),
                    rs.getInt("jumlah"),
                    rs.getDouble("total")
                });
            }
            
            // load tanggal transaksi
            query = "SELECT tanggal FROM transactions WHERE id_transaksi = ?";
            ps = Vconn.prepareStatement(query);
            ps.setString(1, idTransaksi);
            rs = ps.executeQuery();
            
            if (rs.next()) {
                finputtgl.setText(rs.getString("tanggal"));
            } else {
                JOptionPane.showMessageDialog(this, "ID Transaksi tidak ditemukan!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
        }
    }
    
    private void SaveReturn() {
        int row = ftbldetailtsc.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu!");
            return;
        }

        String idTransaksi = finputidtsc.getText();
        String idItem = ftbldetailtsc.getValueAt(row, 0).toString();

        // ambil dan cek nilai jumlah asli dengan aman
        Object val = ftbldetailtsc.getValueAt(row, 1);

        if(val == null || val.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah asli kosong atau tidak valid.");
            return;
        }

        int jumlahAsli;
        try {
            jumlahAsli = Integer.parseInt(val.toString());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah asli tidak valid.");
            return;
        }

        int jumlahReturn;
        try {
            jumlahReturn = Integer.parseInt(fjumlahretur.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah return harus berupa angka.");
            return;
        }

        // Validasi jumlah return
        if (jumlahReturn > jumlahAsli || jumlahReturn <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah return tidak valid.");
            return;
        }

        String tanggalReturn = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

        // Validasi tanggal maksimal return (3 hari)
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggalTransaksi = sdf.parse(finputtgl.getText());
            Date tanggalSekarang = new Date();

            long selisih = tanggalSekarang.getTime() - tanggalTransaksi.getTime();
            long selisihHari = selisih / (1000 * 60 * 60 * 24);

            if (selisihHari > 3) {
                JOptionPane.showMessageDialog(this, "Return hanya bisa dilakukan maksimal 3 hari setelah transaksi.");
                return;
            }

            java.sql.Connection Vconn = null;
            java.sql.PreparedStatement pstInsert = null;
            java.sql.PreparedStatement pstUpdate = null;

            try {
                Vconn = Koneksi.konfigDB();

                // Simpan ke tabel return
                String insert = "INSERT INTO returns (id_transaksi, id_item, jumlah, tanggal_return) VALUES (?, ?, ?, ?)";
                pstInsert = Vconn.prepareStatement(insert);
                pstInsert.setString(1, idTransaksi);
                pstInsert.setString(2, idItem);
                pstInsert.setInt(3, jumlahReturn);
                pstInsert.setString(4, tanggalReturn);
                pstInsert.executeUpdate();

                // Update stok (menambah stok karena return barang)
                String updateStok = "UPDATE items SET stok = stok + ? WHERE id_item = ?";
                pstUpdate = Vconn.prepareStatement(updateStok);
                pstUpdate.setInt(1, jumlahReturn);
                pstUpdate.setString(2, idItem);
                pstUpdate.executeUpdate();

                JOptionPane.showMessageDialog(this, "Return berhasil disimpan.");
                fjumlahretur.setText("");
                loadBarangTransaksi(idTransaksi); // Refresh data
                loadReturnTable();
                resetFormReturn();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error saat simpan return: " + e.getMessage());
            } finally {
                try {
                    if (pstInsert != null) pstInsert.close();
                    if (pstUpdate != null) pstUpdate.close();
                    if (Vconn != null) Vconn.close();
                } catch (Exception ex) {
                    // Ignore atau log error saat menutup Koneksi
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Format tanggal transaksi tidak valid.");
        }
    }
    
    public void loadReturnTable() {
        DefaultTableModel tblModel = (DefaultTableModel) ftblreturn.getModel();
        tblModel.setRowCount(0);
        
        try (java.sql.Connection Vconn = Koneksi.konfigDB()) {
            String query = "SELECT * FROM returns ORDER BY tanggal_return DESC";
            java.sql.PreparedStatement ps = Vconn.prepareStatement(query);
            java.sql.ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                tblModel.addRow(new Object[] {
                    rs.getInt("id_return"),
                    rs.getString("id_transaksi"),
                    rs.getString("id_item"),
                    rs.getInt("jumlah"),
                    rs.getString("tanggal_return")
                });
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error saat load return : " + e.getMessage());
        }

    }
    
    public void resetFormReturn() {
        finputidtsc.setText("");
        finputtgl.setText("");
        fjumlahretur.setText("");
        
        DefaultTableModel tblModel = (DefaultTableModel) ftbldetailtsc.getModel();
        tblModel.setRowCount(0);
    }

    /**
     * Method untuk toggle fullscreen mode
     * @param fullscreen true untuk fullscreen, false untuk windowed
     */
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBarang().setVisible(true);
            }
        });
    }
    
    private void loadnama() {
                int idUser = Login.Session.getUserId();
                String nama = "";
                try {
                    java.sql.Connection Vconn = (Connection)Koneksi.konfigDB();
                    String sql = "SELECT nama FROM users WHERE id_user = ?";
                    java.sql.PreparedStatement s = Vconn.prepareStatement(sql);
                    s.setInt(1, idUser);
                    ResultSet rs = s.executeQuery();

                    if (rs.next()) {
                        nama = rs.getString("nama");
                    }

                    rs.close();
                    s.close();
                    Vconn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                profileNameLabel.setText(""+nama+"");
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JButton fbtnbatal;
    private javax.swing.JButton fbtncek;
    private javax.swing.JButton fbtnsvreturn;
    private javax.swing.JTextField finputidtsc;
    private javax.swing.JTextField finputtgl;
    private javax.swing.JTextField fjumlahretur;
    private javax.swing.JTable ftbldetailtsc;
    private javax.swing.JTable ftblreturn;
    private javax.swing.JLabel historiTransaksiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listBarangBtn;
    private javax.swing.JLabel listBarangBtnIcon;
    private javax.swing.JLabel logoTitleLabel1;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JLabel profileRoleLabel;
    private javax.swing.JLabel returnBarangBtn;
    private javax.swing.JLabel returnBarangBtnIcon;
    private javax.swing.JLabel returnBarangIcon;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel transaksiBtn;
    private javax.swing.JLabel transaksiBtnIcon;
    // End of variables declaration//GEN-END:variables
}

