/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nabil
 */
public class ReturnBarang extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBarang
     */
    public ReturnBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        finputidtsc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        finputtgl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftbldetailtsc = new javax.swing.JTable();
        fbtnsvreturn = new javax.swing.JButton();
        fbtnbatal = new javax.swing.JButton();
        fbtncek = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fjumlahretur = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ftblreturn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Return Barang");

        jPanel1.setBackground(new java.awt.Color(237, 255, 249));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Toko");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 142, 110));
        jLabel2.setText("Aja.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/home (1).png"))); // NOI18N
        jLabel3.setText(" Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/transaction.png"))); // NOI18N
        jLabel4.setText(" Transaksi");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/barang.png"))); // NOI18N
        jLabel5.setText(" Return Barang");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/history.png"))); // NOI18N
        jLabel6.setText(" Histori Transaksi");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/logout.png"))); // NOI18N
        jLabel7.setText(" Log Out");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/profile icon.png"))); // NOI18N
        jLabel8.setText(" Nabila");

        jLabel9.setText("Kasir");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\nabil\\Downloads\\Dokumen - Copy (2)\\KULIAH\\TUGAS SEMESTER 4\\PBO\\SistemManajemenToko-main\\src\\pbo_manajemen_toko\\icons\\boxes.png")); // NOI18N
        jLabel13.setText(" List Barang");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel9)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(87, 87, 87))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(50, 142, 110));
        jLabel10.setText("Return Barang");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setText("ID Transaksi");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel14.setText("Tanggal");

        finputtgl.setEditable(false);
        finputtgl.setEnabled(false);

        ftbldetailtsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Item", "Jumlah", "Total"
            }
        ));
        ftbldetailtsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftbldetailtscMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ftbldetailtsc);

        fbtnsvreturn.setBackground(new java.awt.Color(204, 0, 0));
        fbtnsvreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fbtnsvreturn.setForeground(new java.awt.Color(255, 255, 255));
        fbtnsvreturn.setText("Simpan Return");
        fbtnsvreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtnsvreturnActionPerformed(evt);
            }
        });

        fbtnbatal.setBackground(new java.awt.Color(50, 142, 110));
        fbtnbatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fbtnbatal.setForeground(new java.awt.Color(255, 255, 255));
        fbtnbatal.setText("Batal");
        fbtnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtnbatalActionPerformed(evt);
            }
        });

        fbtncek.setBackground(new java.awt.Color(50, 142, 110));
        fbtncek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fbtncek.setForeground(new java.awt.Color(255, 255, 255));
        fbtncek.setText("Cek Transaksi");
        fbtncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtncekActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Jumlah Return");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fbtncek))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(finputidtsc)
                                    .addComponent(finputtgl, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fjumlahretur, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fbtnsvreturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fbtnbatal)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(finputidtsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finputtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(fbtncek)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fjumlahretur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fbtnbatal)
                    .addComponent(fbtnsvreturn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText(">> Data Return");

        ftblreturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Return", "ID Transaksi", "ID Item", "Jumlah Return", "Tanggal Return"
            }
        ));
        jScrollPane2.setViewportView(ftblreturn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        DashboardKasir dsb = new DashboardKasir();
        dsb.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int idUser = 1;
        TransaksiKasir transaksi = new TransaksiKasir(idUser);
        transaksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        HistoriKasir hst = new HistoriKasir();
        hst.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void fbtncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtncekActionPerformed
        // TODO add your handling code here:
        String id = finputidtsc.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID Transaksi terlebih dahulu");
            return;
        }
        loadBarangTransaksi(id);
    }//GEN-LAST:event_fbtncekActionPerformed

    private void ftbldetailtscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftbldetailtscMouseClicked
        // TODO add your handling code here:
        int row = ftbldetailtsc.getSelectedRow();
        if (row != -1) {
            
        }
    }//GEN-LAST:event_ftbldetailtscMouseClicked

    private void fbtnsvreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtnsvreturnActionPerformed
        // TODO add your handling code here:
        SaveReturn();
    }//GEN-LAST:event_fbtnsvreturnActionPerformed

    private void fbtnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtnbatalActionPerformed
        // TODO add your handling code here:
        finputidtsc.setText("");
        finputtgl.setText("");
        fjumlahretur.setText("");
        ((DefaultTableModel) ftbldetailtsc.getModel()).setRowCount(0);
    }//GEN-LAST:event_fbtnbatalActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        ListBarang lstB = new ListBarang();
        lstB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked
    
    
    private void loadBarangTransaksi(String idTransaksi) {
        DefaultTableModel tblModel = (DefaultTableModel) ftbldetailtsc.getModel();
        tblModel.setRowCount(0);
        
        try(java.sql.Connection Vconn = koneksi.konfigDB()) {
            String query = "SELECT id_item, jumlah, subtotal AS total " + "FROM transaction_items WHERE id_transaksi = ?";
            java.sql.PreparedStatement ps = Vconn.prepareStatement(query);
            ps.setString(1, idTransaksi);
            java.sql.ResultSet rs = ps.executeQuery();
            
            tblModel.setRowCount(0);
            
            while (rs.next()) {
                tblModel.addRow(new Object[] {
                    rs.getString("id_item"),
                    rs.getInt("jumlah"),
                    rs.getDouble("total")
                });
            }
            
            // load tanggal transaksi
            query = "SELECT tanggal FROM transactions WHERE id_transaksi = ?";
            ps = Vconn.prepareStatement(query);
            ps.setString(1, idTransaksi);
            rs = ps.executeQuery();
            
            if (rs.next()) {
                finputtgl.setText(rs.getString("tanggal"));
            } else {
                JOptionPane.showMessageDialog(this, "ID Transaksi tidak ditemukan!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
        }
    }
    
    private void SaveReturn() {
        int row = ftbldetailtsc.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu!");
            return;
        }

        String idTransaksi = finputidtsc.getText();
        String idItem = ftbldetailtsc.getValueAt(row, 0).toString();

        // ambil dan cek nilai jumlah asli dengan aman
        Object val = ftbldetailtsc.getValueAt(row, 1);

        if(val == null || val.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah asli kosong atau tidak valid.");
            return;
        }

        int jumlahAsli;
        try {
            jumlahAsli = Integer.parseInt(val.toString());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah asli tidak valid.");
            return;
        }

        int jumlahReturn;
        try {
            jumlahReturn = Integer.parseInt(fjumlahretur.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah return harus berupa angka.");
            return;
        }

        // Validasi jumlah return
        if (jumlahReturn > jumlahAsli || jumlahReturn <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah return tidak valid.");
            return;
        }

        String tanggalReturn = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

        // Validasi tanggal maksimal return (3 hari)
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggalTransaksi = sdf.parse(finputtgl.getText());
            Date tanggalSekarang = new Date();

            long selisih = tanggalSekarang.getTime() - tanggalTransaksi.getTime();
            long selisihHari = selisih / (1000 * 60 * 60 * 24);

            if (selisihHari > 3) {
                JOptionPane.showMessageDialog(this, "Return hanya bisa dilakukan maksimal 3 hari setelah transaksi.");
                return;
            }

            java.sql.Connection Vconn = null;
            java.sql.PreparedStatement pstInsert = null;
            java.sql.PreparedStatement pstUpdate = null;

            try {
                Vconn = koneksi.konfigDB();

                // Simpan ke tabel return
                String insert = "INSERT INTO returns (id_transaksi, id_item, jumlah, tanggal_return) VALUES (?, ?, ?, ?)";
                pstInsert = Vconn.prepareStatement(insert);
                pstInsert.setString(1, idTransaksi);
                pstInsert.setString(2, idItem);
                pstInsert.setInt(3, jumlahReturn);
                pstInsert.setString(4, tanggalReturn);
                pstInsert.executeUpdate();

                // Update stok (menambah stok karena return barang)
                String updateStok = "UPDATE items SET stok = stok + ? WHERE id_item = ?";
                pstUpdate = Vconn.prepareStatement(updateStok);
                pstUpdate.setInt(1, jumlahReturn);
                pstUpdate.setString(2, idItem);
                pstUpdate.executeUpdate();

                JOptionPane.showMessageDialog(this, "Return berhasil disimpan.");
                fjumlahretur.setText("");
                loadBarangTransaksi(idTransaksi); // Refresh data
                loadReturnTable();
                resetFormReturn();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error saat simpan return: " + e.getMessage());
            } finally {
                try {
                    if (pstInsert != null) pstInsert.close();
                    if (pstUpdate != null) pstUpdate.close();
                    if (Vconn != null) Vconn.close();
                } catch (Exception ex) {
                    // Ignore atau log error saat menutup koneksi
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Format tanggal transaksi tidak valid.");
        }
    }
    
    public void loadReturnTable() {
        DefaultTableModel tblModel = (DefaultTableModel) ftblreturn.getModel();
        tblModel.setRowCount(0);
        
        try (java.sql.Connection Vconn = koneksi.konfigDB()) {
            String query = "SELECT * FROM returns ORDER BY tanggal_return DESC";
            java.sql.PreparedStatement ps = Vconn.prepareStatement(query);
            java.sql.ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                tblModel.addRow(new Object[] {
                    rs.getInt("id_return"),
                    rs.getString("id_transaksi"),
                    rs.getString("id_item"),
                    rs.getInt("jumlah"),
                    rs.getString("tanggal_return")
                });
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error saat load return : " + e.getMessage());
        }

    }
    
    public void resetFormReturn() {
        finputidtsc.setText("");
        finputtgl.setText("");
        fjumlahretur.setText("");
        
        DefaultTableModel tblModel = (DefaultTableModel) ftbldetailtsc.getModel();
        tblModel.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fbtnbatal;
    private javax.swing.JButton fbtncek;
    private javax.swing.JButton fbtnsvreturn;
    private javax.swing.JTextField finputidtsc;
    private javax.swing.JTextField finputtgl;
    private javax.swing.JTextField fjumlahretur;
    private javax.swing.JTable ftbldetailtsc;
    private javax.swing.JTable ftblreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
