/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Syahrul Ramadhan
 */
public class TambahBarang extends javax.swing.JFrame {

    /**
     * Creates new form TambahBarang
     */
    
    Barang barang;
    
    public TambahBarang(Barang barang) {
        this.barang= barang;
        initComponents();
    }

    private TambahBarang() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNama = new javax.swing.JTextField();
        textFieldStok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldHarga = new javax.swing.JTextField();
        simpanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 150));
        setResizable(false);

        tittle.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        tittle.setText("Tambah Barang");

        jLabel1.setText("Nama Barang :");

        textFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaActionPerformed(evt);
            }
        });

        textFieldStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldStokActionPerformed(evt);
            }
        });

        jLabel2.setText("Stok                 :");

        jLabel3.setText("Harga Satuan :");

        textFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHargaActionPerformed(evt);
            }
        });

        simpanBtn.setBackground(new java.awt.Color(50, 142, 110));
        simpanBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(255, 255, 255));
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textFieldNama)
                    .addComponent(simpanBtn)
                    .addComponent(textFieldHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(textFieldStok)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tittle)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(tittle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(simpanBtn)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaActionPerformed

    private void textFieldStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldStokActionPerformed

    private void textFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldHargaActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nama = textFieldNama.getText();
        String stok = textFieldStok.getText();
        String harga = textFieldHarga.getText();
        
        if (nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Nama Terlebih Dahulu");
        } else if (stok.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Stok Terlebih Dahulu");
        } else if (harga.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Harga Terlebih Dahulu");
        }
        else {
            try {
                // Validasi angka
                int stokInt = Integer.parseInt(stok);       // cek stok adalah integer
                double hargaDouble = Double.parseDouble(harga); // cek harga adalah desimal
        
                String query = "INSERT INTO items (nama_item, stok, harga) VALUES ( ?, ?, ?)";
                java.sql.Connection Vconn = (Connection) Koneksi.konfigDB();
                java.sql.PreparedStatement s = Vconn.prepareStatement(query);
                s.setString(1, nama);
                s.setInt(2, stokInt);
                s.setDouble(3, hargaDouble);
                s.execute();

                //tambah ke histori
                String aktivitas = "menambahkan data barang:"+nama;
                String logQuery = "INSERT INTO history (id_user, aktivitas) VALUES (?, ?)";
                java.sql.PreparedStatement logS = Vconn.prepareStatement(logQuery);
                logS.setInt(1, Login.Session.getUserId());
                logS.setString(2, aktivitas);
                logS.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data");
                
                barang.tampil_tabel_barang();
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Stok harus angka dan harga harus berupa angka/desimal");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menambahkan Data");
                JOptionPane.showMessageDialog(this, e.getMessage()); 
            }
            
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTextField textFieldHarga;
    private javax.swing.JTextField textFieldNama;
    private javax.swing.JTextField textFieldStok;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
