/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

import java.sql.Connection;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author nabil
 */
public class TransaksiKasir extends javax.swing.JFrame {
    private double subtotal = 0.0;
    private double total = 0.0;
    private int idUser;
    private DefaultTableModel tblModel;
    private int nomorUrut = 1;
  
    
    /**
     * Creates new form TransaksiKasir
     */
    public TransaksiKasir(int idUser) {
        initComponents();
        this.idUser = idUser;
        
        tblModel = (DefaultTableModel) ftbltransaksi.getModel();
        loadDiskon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        finput = new javax.swing.JTextField();
        fjumlah = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ftotal2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftbltransaksi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        fdiskon = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        fpajak = new javax.swing.JTextField();
        fsubtotal1 = new javax.swing.JLabel();
        fsubtotal = new javax.swing.JLabel();
        ftotal1 = new javax.swing.JLabel();
        ftotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi Kasir");

        jPanel1.setBackground(new java.awt.Color(237, 255, 249));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Toko");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 142, 110));
        jLabel2.setText("Aja.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/home (1).png"))); // NOI18N
        jLabel3.setText(" Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/transaction.png"))); // NOI18N
        jLabel4.setText(" Transaksi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/barang.png"))); // NOI18N
        jLabel5.setText(" Return Barang");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/history.png"))); // NOI18N
        jLabel6.setText(" Histori Transaksi");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/profile icon.png"))); // NOI18N
        jLabel7.setText(" Nabila");

        jLabel8.setText("Kasir");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/logout.png"))); // NOI18N
        jLabel9.setText(" Log Out");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/boxes.png"))); // NOI18N
        jLabel12.setText("  List Barang");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(148, 148, 148)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(50, 142, 110));
        jLabel10.setText("Transaksi");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/add.png"))); // NOI18N
        jButton1.setText("Tambah Barang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finput.setText("Masukkan id/nama barang");
        finput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                finputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                finputFocusLost(evt);
            }
        });

        fjumlah.setText("Jumlah");
        fjumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fjumlahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fjumlahFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(50, 142, 110));
        jLabel11.setText("Total");

        ftotal2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ftotal2.setText("Rp. 0");

        ftbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Id_transaksi", "Id_item", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(ftbltransaksi);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Diskon");

        fdiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih" }));
        fdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdiskonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Pajak");

        fpajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpajakActionPerformed(evt);
            }
        });

        fsubtotal1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        fsubtotal1.setText("Sub Total");

        fsubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fsubtotal.setText("Rp. 0");

        ftotal1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ftotal1.setForeground(new java.awt.Color(50, 142, 110));
        ftotal1.setText("Total");

        ftotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ftotal.setForeground(new java.awt.Color(50, 142, 110));
        ftotal.setText("Rp. 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fdiskon, 0, 98, Short.MAX_VALUE)
                    .addComponent(fpajak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fsubtotal1)
                    .addComponent(ftotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fsubtotal)
                    .addComponent(ftotal))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fsubtotal1)
                    .addComponent(fsubtotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fpajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftotal1)
                    .addComponent(ftotal))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(50, 142, 110));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_manajemen_toko/icons/shopping-cart.png"))); // NOI18N
        jButton2.setText("Bayar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 748, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(finput, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(fjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ftotal2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(177, 177, 177)))
                .addGap(223, 223, 223))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(finput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(ftotal2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        DashboardKasir dsb = new DashboardKasir();
        dsb.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        ReturnBarang rtrB = new ReturnBarang();
        rtrB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        HistoriKasir hst = new HistoriKasir();
        hst.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tambahBarang();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finputFocusGained
        // TODO add your handling code here:
        if (finput.getText().equals("Masukkan id/nama barang")) {
            finput.setText("");
        }
        
    }//GEN-LAST:event_finputFocusGained

    private void finputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finputFocusLost
        // TODO add your handling code here:
        if (finput.getText().isEmpty()) {
            finput.setText("Masukkan id/nama barang");
        }
    }//GEN-LAST:event_finputFocusLost

    private void fjumlahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fjumlahFocusGained
        // TODO add your handling code here:
        if (fjumlah.getText().equals("Jumlah")) {
            fjumlah.setText("");
        }
    }//GEN-LAST:event_fjumlahFocusGained

    private void fjumlahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fjumlahFocusLost
        // TODO add your handling code here:
        if (fjumlah.getText().isEmpty()) {
            fjumlah.setText("Jumlah");
        }
    }//GEN-LAST:event_fjumlahFocusLost

    private void fdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdiskonActionPerformed
        // TODO add your handling code here:
        updateTotal();
    }//GEN-LAST:event_fdiskonActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        bayar();
    }//GEN-LAST:event_jButton2MouseClicked

    private void fpajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpajakActionPerformed
        // TODO add your handling code here:
        updateTotal();
    }//GEN-LAST:event_fpajakActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        ListBarang lstB = new ListBarang();
        lstB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked
    

    private void resetFormInput() {
        finput.setText("Masukkan id/nama barang");
        fjumlah.setText("Jumlah");
    }
    
    private void loadDiskon() {
        try {
            // query
            String query = "SELECT kode_diskon FROM diskon WHERE aktif = 1";
            
            // fungsi koneksi
            java.sql.Connection Vconn = (Connection)koneksi.konfigDB();
            
            // kirim parameter fungsi java ke sql
            java.sql.Statement s = Vconn.createStatement();
            
            // eksekusi query
            java.sql.ResultSet rs = s.executeQuery(query);
            
            // looping
            while (rs.next()) {
                fdiskon.addItem(rs.getString("kode_diskon"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void tambahBarang() {
        String keyword = finput.getText();
        int jumlah = Integer.parseInt(fjumlah.getText());
        try {
            java.sql.Connection Vconn = koneksi.konfigDB();
            java.sql.PreparedStatement ps = Vconn.prepareStatement("SELECT * FROM items WHERE id_item=? OR nama_item LIKE ?");
            ps.setString(1, keyword);
            ps.setString(2, "%" + keyword + "%");
            java.sql.ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                String idItem = rs.getString("id_item");
                double harga = rs.getDouble("harga");
                int stok = rs.getInt("stok");
                
                //cek stok cukup 
                if (jumlah > stok) {
                    JOptionPane.showMessageDialog(this, "Stok untuk \"" + idItem + "\" tidak mencukupi.\nStok tersedia: " + stok, "Stok tidak cukup", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                double totalItem = harga * jumlah;
                subtotal += totalItem;
                updateTotal();
                
                
                Vector<Object> row = new Vector<>();
                row.add(nomorUrut++);
                row.add("");
                row.add(idItem);
                row.add(jumlah);
                row.add(totalItem);
                tblModel.addRow(row);
                
                resetFormInput();
                updateTotal();
            } else {
                JOptionPane.showMessageDialog(this, "item tidak ditemukan");
            }
        } catch (Exception e ) {
            e.printStackTrace();
        }
    }
    
    private void updateTotal() {
        try {
            double pajak = fpajak.getText().isEmpty() ? 0 : Double.parseDouble(fpajak.getText());
            String kodeDiskon = (String) fdiskon.getSelectedItem();
            
            double diskonValue = 0;
            try {
                java.sql.Connection Vconn = koneksi.konfigDB();
                java.sql.PreparedStatement ps = Vconn.prepareStatement("SELECT * FROM diskon WHERE kode_diskon = ?");
                ps.setString(1, kodeDiskon);
                java.sql.ResultSet rs = ps.executeQuery();
                if(rs.next()) {
                    double nilai = rs.getDouble("nilai");
                    String tipe = rs.getString("tipe");
                    diskonValue = tipe.equalsIgnoreCase("persentase") ? subtotal * nilai / 100 : nilai;
                }
            } catch (Exception e) {
                
            }
            
            // setelah diskon
            double setelahDiskon = subtotal - diskonValue;
            
            // Hitung pajak dari nilai setelah diskon
            double pajakValue = setelahDiskon * pajak / 100;
            
            //total akhir
            double total = setelahDiskon + pajakValue;
                    
            fsubtotal.setText(String.format("Rp. %.0f", subtotal));
            ftotal.setText(String.format("Rp. %.0f", total));
            ftotal2.setText(String.format("Rp. %.0f", total));
        } catch (Exception e) {
            e.printStackTrace();
          
        }
    }
    
    private void bayar() {
    java.sql.Connection Vconn = null;
    try {
        Vconn = koneksi.konfigDB();
        Vconn.setAutoCommit(false);

        // Hitung subtotal dari tabel
        double subtotal = 0.0;
        for (int i = 0; i < ftbltransaksi.getRowCount(); i++) {
            Object subTotalObj = ftbltransaksi.getValueAt(i, 4);
            if (subTotalObj != null) {
                subtotal += Double.parseDouble(subTotalObj.toString());
            }
        }

        // Ambil diskon
        String kodeDiskon = (String) fdiskon.getSelectedItem();
        Integer idDiskon = null;
        double diskonValue = 0.0;

        if (kodeDiskon != null && !kodeDiskon.isEmpty()) {
            try (java.sql.PreparedStatement psDiskon = Vconn.prepareStatement("SELECT id_diskon, tipe, nilai FROM diskon WHERE kode_diskon=?")) {
                psDiskon.setString(1, kodeDiskon);
                try (java.sql.ResultSet rsDiskon = psDiskon.executeQuery()) {
                    if (rsDiskon.next()) {
                        idDiskon = rsDiskon.getInt("id_diskon");
                        String tipe = rsDiskon.getString("tipe");
                        double nilai = rsDiskon.getDouble("nilai");

                        if ("persentase".equalsIgnoreCase(tipe)) {
                            diskonValue = subtotal * nilai / 100;
                        } else {
                            diskonValue = nilai;
                        }
                    }
                }
            }
        }

        // Ambil nilai pajak dari input
        double pajak = 0.0;
        try {
            pajak = Double.parseDouble(fpajak.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nilai pajak tidak valid. Diset 0.");
        }

        // Hitung total
        double setelahDiskon = subtotal - diskonValue;
        double pajakValue = setelahDiskon * pajak / 100;
        total = setelahDiskon + pajakValue;

        // Debug
        System.out.println("Subtotal: " + subtotal);
        System.out.println("Diskon: " + diskonValue);
        System.out.println("Pajak: " + pajakValue);
        System.out.println("Total: " + total);

        // Simpan transaksi utama
        int idTransaksi = 0;
        try (java.sql.PreparedStatement ps = Vconn.prepareStatement(
                "INSERT INTO transactions (id_user, id_diskon, total_harga, tanggal) VALUES (?, ?, ?, NOW())",
                java.sql.PreparedStatement.RETURN_GENERATED_KEYS)) {

            ps.setInt(1, idUser);
            if (idDiskon == null) {
                ps.setNull(2, java.sql.Types.INTEGER);
            } else {
                ps.setInt(2, idDiskon);
            }
            ps.setDouble(3, total);
            ps.executeUpdate();

            try (java.sql.ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    idTransaksi = rs.getInt(1);
                } else {
                    throw new SQLException("Gagal mendapatkan ID Transaksi.");
                }
            }
        }

        // Simpan detail item transaksi dan kurangi stok
        for (int i = 0; i < ftbltransaksi.getRowCount(); i++) {
            Object idItemObj = ftbltransaksi.getValueAt(i, 2);
            Object jumlahObj = ftbltransaksi.getValueAt(i, 3);
            Object subTotalItemObj = ftbltransaksi.getValueAt(i, 4);

            if (idItemObj == null || jumlahObj == null || subTotalItemObj == null) {
                System.out.println("Baris " + i + " kosong, dilewati.");
                continue;
            }

            String idItem = idItemObj.toString();
            int jumlah = Integer.parseInt(jumlahObj.toString());
            double subTotalItem = Double.parseDouble(subTotalItemObj.toString());
            
            // simpan ke detail transaksi
            try (java.sql.PreparedStatement pDetail = Vconn.prepareStatement(
                    "INSERT INTO transaction_items (id_transaksi, id_item, jumlah, subtotal) VALUES (?, ?, ?, ?)")) {
                pDetail.setInt(1, idTransaksi);
                pDetail.setString(2, idItem);
                pDetail.setInt(3, jumlah);
                pDetail.setDouble(4, subTotalItem);
                pDetail.executeUpdate();
            }
            
            // kurangi stok barang
            try (java.sql.PreparedStatement pstStok = Vconn.prepareStatement("UPDATE items SET stok = stok - ? WHERE id_item = ?")) {
                pstStok.setInt(1, jumlah);
                pstStok.setString(2, idItem);
                pstStok.executeUpdate();
            }
        }

        Vconn.commit();
        
        // simpan histori transaksi
        String aktivitas = "Melakukan transaksi penjualan dengan ID transaksi " + idTransaksi;
        insertHistori(idUser, aktivitas);
    
        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan.");
        resetForm();

    } catch (Exception e) {
        try {
            if (Vconn != null) {
                Vconn.rollback();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal simpan transaksi: " + e.getMessage());
    } finally {
        try {
            if (Vconn != null && !Vconn.isClosed()) {
                Vconn.setAutoCommit(true);
                Vconn.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }

    private void insertHistori(int idUser, String aktivitas) {
        try (java.sql.Connection Vconn = koneksi.konfigDB()) {
            String sql = "INSERT INTO history (id_user, aktivitas, waktu) VALUES (?, ?, NOW())";
            java.sql.PreparedStatement pst = Vconn.prepareStatement(sql);
            pst.setInt(1, idUser);
            pst.setString(2, aktivitas);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan histori: " + e.getMessage());
        }
    }

    private void resetForm() {
        finput.setText("Masukkan id/nama barang");
        fjumlah.setText("Jumlah");
        fdiskon.setSelectedIndex(0);
        fpajak.setText("");
        
        DefaultTableModel tblModel = (DefaultTableModel) ftbltransaksi.getModel();
        tblModel.setRowCount(0);
        
        nomorUrut = 1;
        subtotal = 0;
        total = 0;
        updateTotal();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TransaksiKasir().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fdiskon;
    private javax.swing.JTextField finput;
    private javax.swing.JTextField fjumlah;
    private javax.swing.JTextField fpajak;
    private javax.swing.JLabel fsubtotal;
    private javax.swing.JLabel fsubtotal1;
    private javax.swing.JTable ftbltransaksi;
    private javax.swing.JLabel ftotal;
    private javax.swing.JLabel ftotal1;
    private javax.swing.JLabel ftotal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
