/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_manajemen_toko;

import manajemen_toko.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Syahrul Ramadhan
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public User() {
        initComponents();
        
        //auto fullscreen
        setExtendedState(User.MAXIMIZED_BOTH);
        //bg warna putih
        getContentPane().setBackground(new Color(250, 250, 250));
        
        tampil_tabel_user();
        loadnama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashbaordBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barangBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dashbaordLabel6 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_user = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideBar.setBackground(new java.awt.Color(237, 255, 249));
        sideBar.setForeground(new java.awt.Color(237, 255, 249));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 142, 110));
        jLabel2.setText("TokoAja.");

        dashbaordBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordBtn.setForeground(new java.awt.Color(123, 122, 120));
        dashbaordBtn.setText("Dashboard");
        dashbaordBtn.setToolTipText("");
        dashbaordBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dashbaordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashbaordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbaordBtnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame.png"))); // NOI18N

        barangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        barangBtn.setForeground(new java.awt.Color(123, 122, 120));
        barangBtn.setText("Barang");
        barangBtn.setToolTipText("");
        barangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        barangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangBtnMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box-1.png"))); // NOI18N

        userBtn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        userBtn.setForeground(new java.awt.Color(50, 142, 110));
        userBtn.setText("User");
        userBtn.setToolTipText("");
        userBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame-3.png"))); // NOI18N

        historyBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(123, 122, 120));
        historyBtn.setText("Histori");
        historyBtn.setToolTipText("");
        historyBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        historyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/transaction-history-stroke-rounded 1.png"))); // NOI18N

        logoutBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(123, 122, 120));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/logout.png"))); // NOI18N

        label_nama.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        label_nama.setText("Icibos");
        label_nama.setToolTipText("");
        label_nama.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/profile-img.png"))); // NOI18N

        dashbaordLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordLabel6.setForeground(new java.awt.Color(123, 122, 120));
        dashbaordLabel6.setText("Super-admin");
        dashbaordLabel6.setToolTipText("");
        dashbaordLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashbaordBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama)
                            .addComponent(dashbaordLabel6)))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashbaordBtn)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barangBtn)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userBtn)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historyBtn)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(label_nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashbaordLabel6)))
                .addGap(28, 28, 28)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41))
        );

        tittle.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        tittle.setForeground(new java.awt.Color(50, 142, 110));
        tittle.setText("Manajemen User");

        searchField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        searchField.setSelectionColor(new java.awt.Color(50, 142, 110));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(50, 142, 110));
        searchBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(50, 142, 110));
        addBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/add.png"))); // NOI18N
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        tabel_user.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tabel_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id User", "Username", "Nama", "Role", "Password", "Terakhir Diperbarui"
            }
        ));
        jScrollPane1.setViewportView(tabel_user);

        editBtn.setBackground(new java.awt.Color(50, 142, 110));
        editBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/edit-02-Stroke-Rounded.png"))); // NOI18N
        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(50, 142, 110));
        deleteBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/delete-02-Stroke-Rounded.png"))); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(50, 142, 110));
        resetBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tittle)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
        String keyword = searchField.getText();
        cariData(keyword);
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String keyword = searchField.getText();
        cariData(keyword);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        TambahUser tambahUser = new TambahUser(this);
        tambahUser.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_user.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
            return;
        }

        String id = tabel_user.getValueAt(selectedRow, 0).toString();
        String username = tabel_user.getValueAt(selectedRow, 1).toString();
        String nama = tabel_user.getValueAt(selectedRow, 2).toString();
        String role = tabel_user.getValueAt(selectedRow, 3).toString();
        String password = tabel_user.getValueAt(selectedRow, 4).toString();

        // Kirim ke frame EditBarang
        EditUser editFrame = new EditUser(this, id, username, nama, role, password);
        editFrame.setVisible(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int baris = tabel_user.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!");
            return;
        }
        
        //ambil id dari tabel
        String id = tabel_user.getValueAt(baris,0).toString();
        String username = tabel_user.getValueAt(baris,1).toString();
        
        int konfirmasi = JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus data ini?", 
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection Vconn = (Connection)KoneksiDB.configDB();
                
                //tambah ke histori
                String aktivitas = "menghapus data user:"+username;
                String logQuery = "INSERT INTO history (id_user, aktivitas) VALUES (?, ?)";
                java.sql.PreparedStatement logS = Vconn.prepareStatement(logQuery);
                logS.setInt(1, Login.Session.getUserId());
                logS.setString(2, aktivitas);
                logS.executeUpdate();
                
                String query = "DELETE FROM users WHERE id_user=?";
                java.sql.PreparedStatement s = Vconn.prepareStatement(query);
                s.setString(1, id);
                s.executeUpdate();
                
                tampil_tabel_user();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
                JOptionPane.showMessageDialog(this, e.getMessage()); 
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void dashbaordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbaordBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_dashbaordBtnMouseClicked

    private void barangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Barang().setVisible(true);
    }//GEN-LAST:event_barangBtnMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Histori().setVisible(true);
    }//GEN-LAST:event_historyBtnMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        searchField.setText("");
        tampil_tabel_user();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        Login.Session.clearSession();
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }
    
    public void tampil_tabel_user() {
        // membuat objek model pada tabel
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id User");
        tb.addColumn("Username");
        tb.addColumn("Nama");
        tb.addColumn("Role");
        tb.addColumn("Password");
        tb.addColumn("Terakhir Diperbarui");
        
        try {
            // 1. Query
            String query = "SELECT * FROM users";
            
            // 2. Fungsi Koneksi
            java.sql.Connection Vconn = (Connection)KoneksiDB.configDB();
            
            // 3. Kirim parameter fungsi java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
            // 4. Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            // 5. Looping
            while (r.next()) {
                tb.addRow(new Object[] {
                r.getString(1),r.getString(2),r.getString(3),r.getString(5),r.getString(4),r.getString(6)
                });
            }
            tabel_user.setModel(tb);
            
        } catch (Exception e) {
            
        }
        
    }
    
    public void cariData(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id User");
        model.addColumn("Username");
        model.addColumn("Nama");
        model.addColumn("Role");
        model.addColumn("Password");
        model.addColumn("Terakhir Diperbarui");
        
        try {
            String query = "SELECT * FROM users WHERE username LIKE ? OR nama LIKE ? ";
            java.sql.Connection Vconn = (Connection)KoneksiDB.configDB();
            java.sql.PreparedStatement s = Vconn.prepareStatement(query);
            s.setString(1, "%"+keyword+"%");
            s.setString(2, "%"+keyword+"%");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                model.addRow(new Object[] {
                    r.getString("id_user"),
                    r.getString("username"),
                    r.getString("nama"),
                    r.getString("role"),
                    r.getString("password"),
                    r.getString("created_at")
                });
            }
            
            tabel_user.setModel(model);
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencari: "+e.getMessage());
        }
    }
    
    private void loadnama() {
        int idUser = Login.Session.getUserId();
        String nama = "";
        try {
            java.sql.Connection Vconn = (Connection)Koneksi.konfigDB();
            String sql = "SELECT nama FROM users WHERE id_user = ?";
            java.sql.PreparedStatement s = Vconn.prepareStatement(sql);
            s.setInt(1, idUser);
            ResultSet rs = s.executeQuery();
            
            if (rs.next()) {
                nama = rs.getString("nama");
            }
            
            rs.close();
            s.close();
            Vconn.close();
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        label_nama.setText(""+nama+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel barangBtn;
    private javax.swing.JLabel dashbaordBtn;
    private javax.swing.JLabel dashbaordLabel6;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTable tabel_user;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel userBtn;
    // End of variables declaration//GEN-END:variables
}
