/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajemen_toko;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Syahrul Ramadhan
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        //auto fullscreen
        setExtendedState(Dashboard.MAXIMIZED_BOTH);
        //bg warna putih
        getContentPane().setBackground(new Color(250, 250, 250));
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashbaordBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barangBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dashbaordLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dashbaordLabel6 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        totalPendapatanPanel = new javax.swing.JPanel();
        totalPendapatanLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalPendapatanValue = new javax.swing.JLabel();
        totalBarangPanel = new javax.swing.JPanel();
        totalBarangLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalBarangValue = new javax.swing.JLabel();
        barangMasukPanel = new javax.swing.JPanel();
        barangMasukLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        barangMasukValue = new javax.swing.JLabel();
        barangKeluarPanel = new javax.swing.JPanel();
        barangKeluarLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        barangKeluarValue = new javax.swing.JLabel();
        grafikPendapatan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(237, 255, 249));
        sideBar.setForeground(new java.awt.Color(237, 255, 249));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 142, 110));
        jLabel2.setText("TokoAja.");

        dashbaordBtn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        dashbaordBtn.setForeground(new java.awt.Color(50, 142, 110));
        dashbaordBtn.setText("Dashboard");
        dashbaordBtn.setToolTipText("");
        dashbaordBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame-1.png"))); // NOI18N

        barangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        barangBtn.setForeground(new java.awt.Color(123, 122, 120));
        barangBtn.setText("Barang");
        barangBtn.setToolTipText("");
        barangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        barangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangBtnMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box-1.png"))); // NOI18N

        userBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        userBtn.setForeground(new java.awt.Color(123, 122, 120));
        userBtn.setText("User");
        userBtn.setToolTipText("");
        userBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        userBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBtnMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame-2.png"))); // NOI18N

        historyBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(123, 122, 120));
        historyBtn.setText("Histori");
        historyBtn.setToolTipText("");
        historyBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        historyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/transaction-history-stroke-rounded 1.png"))); // NOI18N

        logoutBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(123, 122, 120));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/logout.png"))); // NOI18N

        dashbaordLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordLabel5.setText("Icibos");
        dashbaordLabel5.setToolTipText("");
        dashbaordLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/profile-img.png"))); // NOI18N

        dashbaordLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordLabel6.setForeground(new java.awt.Color(123, 122, 120));
        dashbaordLabel6.setText("Super-admin");
        dashbaordLabel6.setToolTipText("");
        dashbaordLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashbaordBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashbaordLabel5)
                            .addComponent(dashbaordLabel6)))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashbaordBtn)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barangBtn)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userBtn)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historyBtn)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(dashbaordLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashbaordLabel6)))
                .addGap(28, 28, 28)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41))
        );

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dashbaordBtn, jLabel1});

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {barangBtn, jLabel3});

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, userBtn});

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {historyBtn, jLabel5});

        tittle.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        tittle.setForeground(new java.awt.Color(50, 142, 110));
        tittle.setText("Dashboard");

        totalPendapatanPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalPendapatanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        totalPendapatanLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalPendapatanLabel.setText("Total Pendapatan");
        totalPendapatanLabel.setToolTipText("");
        totalPendapatanLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/money-recive.png"))); // NOI18N

        totalPendapatanValue.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        totalPendapatanValue.setText("Total Pendapatan");
        totalPendapatanValue.setToolTipText("");
        totalPendapatanValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout totalPendapatanPanelLayout = new javax.swing.GroupLayout(totalPendapatanPanel);
        totalPendapatanPanel.setLayout(totalPendapatanPanelLayout);
        totalPendapatanPanelLayout.setHorizontalGroup(
            totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalPendapatanPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalPendapatanPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(totalPendapatanValue))
                    .addGroup(totalPendapatanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPendapatanLabel)))
                .addGap(19, 19, 19))
        );
        totalPendapatanPanelLayout.setVerticalGroup(
            totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(totalPendapatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalPendapatanLabel)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalPendapatanValue)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalBarangPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalBarangPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        totalBarangLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalBarangLabel.setText("Total Barang");
        totalBarangLabel.setToolTipText("");
        totalBarangLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box.png"))); // NOI18N

        totalBarangValue.setBackground(new java.awt.Color(255, 255, 255));
        totalBarangValue.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        totalBarangValue.setText("Total Barang");
        totalBarangValue.setToolTipText("");
        totalBarangValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout totalBarangPanelLayout = new javax.swing.GroupLayout(totalBarangPanel);
        totalBarangPanel.setLayout(totalBarangPanelLayout);
        totalBarangPanelLayout.setHorizontalGroup(
            totalBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBarangPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(totalBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalBarangPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(totalBarangValue))
                    .addGroup(totalBarangPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBarangLabel)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        totalBarangPanelLayout.setVerticalGroup(
            totalBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBarangPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(totalBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalBarangLabel)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalBarangValue)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        barangMasukPanel.setBackground(new java.awt.Color(255, 255, 255));
        barangMasukPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        barangMasukLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        barangMasukLabel.setText("Barang Masuk");
        barangMasukLabel.setToolTipText("");
        barangMasukLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box.png"))); // NOI18N

        barangMasukValue.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        barangMasukValue.setText("Barang Masuk");
        barangMasukValue.setToolTipText("");
        barangMasukValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout barangMasukPanelLayout = new javax.swing.GroupLayout(barangMasukPanel);
        barangMasukPanel.setLayout(barangMasukPanelLayout);
        barangMasukPanelLayout.setHorizontalGroup(
            barangMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangMasukPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(barangMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barangMasukPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(barangMasukValue))
                    .addGroup(barangMasukPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangMasukLabel)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        barangMasukPanelLayout.setVerticalGroup(
            barangMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangMasukPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(barangMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barangMasukLabel)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barangMasukValue)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        barangKeluarPanel.setBackground(new java.awt.Color(255, 255, 255));
        barangKeluarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 190, 190)));

        barangKeluarLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        barangKeluarLabel.setText("Barang Keluar");
        barangKeluarLabel.setToolTipText("");
        barangKeluarLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box.png"))); // NOI18N

        barangKeluarValue.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        barangKeluarValue.setText("Barang Keluar");
        barangKeluarValue.setToolTipText("");
        barangKeluarValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout barangKeluarPanelLayout = new javax.swing.GroupLayout(barangKeluarPanel);
        barangKeluarPanel.setLayout(barangKeluarPanelLayout);
        barangKeluarPanelLayout.setHorizontalGroup(
            barangKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangKeluarPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(barangKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barangKeluarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(barangKeluarValue))
                    .addGroup(barangKeluarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangKeluarLabel)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        barangKeluarPanelLayout.setVerticalGroup(
            barangKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangKeluarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(barangKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barangKeluarLabel)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barangKeluarValue)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        grafikPendapatan.setPreferredSize(new java.awt.Dimension(390, 390));

        javax.swing.GroupLayout grafikPendapatanLayout = new javax.swing.GroupLayout(grafikPendapatan);
        grafikPendapatan.setLayout(grafikPendapatanLayout);
        grafikPendapatanLayout.setHorizontalGroup(
            grafikPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        grafikPendapatanLayout.setVerticalGroup(
            grafikPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalPendapatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(totalBarangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(barangMasukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(barangKeluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tittle)
                            .addComponent(grafikPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPendapatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBarangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangMasukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangKeluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(grafikPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Barang().setVisible(true);
    }//GEN-LAST:event_barangBtnMouseClicked

    private void userBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new User().setVisible(true);
    }//GEN-LAST:event_userBtnMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Histori().setVisible(true);
    }//GEN-LAST:event_historyBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }
    
    private void LoadData() {
                
            try {
            // 1. Query
            String query1 = "SELECT SUM(total_harga) FROM transactions";
            String query2 = "SELECT SUM(stok) FROM items";
            String query3 = "SELECT SUM(jumlah) AS total_barang_masuk FROM item_log WHERE tipe = 'masuk';";
            String query4 = "SELECT SUM(jumlah) AS total_barang_masuk FROM item_log WHERE tipe = 'keluar';";
            
            // 2. Fungsi Koneksi
            java.sql.Connection Vconn = (Connection)KoneksiDB.configDB();
            
            // 3. Kirim parameter fungsi java ke SQL
            java.sql.Statement s1 = Vconn.createStatement();
            java.sql.Statement s2 = Vconn.createStatement();
            java.sql.Statement s3 = Vconn.createStatement();
            java.sql.Statement s4 = Vconn.createStatement();
            
            // 4. Eksekusi Query
            java.sql.ResultSet rs1 = s1.executeQuery(query1);
            java.sql.ResultSet rs2 = s2.executeQuery(query2);
            java.sql.ResultSet rs3 = s3.executeQuery(query3);
            java.sql.ResultSet rs4 = s4.executeQuery(query4);
            // 5. menampilkan data
            if (rs1.next()) {
                double pendapatan = rs1.getDouble(1);
                if (!rs1.wasNull()) {
                    totalPendapatanValue.setText("Rp."+String.valueOf(pendapatan));
                } else {
                    totalPendapatanValue.setText("0");
                }
            }
            
            if (rs2.next()) {
                int totalBarang = rs2.getInt(1);
                if (!rs2.wasNull()) {
                    totalBarangValue.setText(String.valueOf(totalBarang));
                } else {
                    totalBarangValue.setText("0");
                }
            }
            
            if (rs3.next()) {
                int totalBarang = rs3.getInt(1);
                if (!rs3.wasNull()) {
                    barangMasukValue.setText(String.valueOf(totalBarang));
                } else {
                    barangMasukValue.setText("0");
                }
            }
            if (rs4.next()) {
                int totalBarang = rs4.getInt(1);
                if (!rs4.wasNull()) {
                    barangKeluarValue.setText(String.valueOf(totalBarang));
                } else {
                    barangKeluarValue.setText("0");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencari: "+e.getMessage());
        }
    }
    
    private void loadGrafik () {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
            Connection Vconn = (Connection) KoneksiDB.configDB(); // koneksi DB kamu
            String query = "SELECT DATE_FORMAT(tanggal, '%Y-%m') AS bulan, SUM(total_harga) AS total " +
                           "FROM transactions GROUP BY bulan ORDER BY bulan";

            java.sql.Statement s = Vconn.createStatement();
            java.sql.ResultSet rs = s.executeQuery(query);

            while (rs.next()) {
                String bulan = rs.getString("bulan");
                double total = rs.getDouble("total");
                dataset.addValue(total, "Pendapatan", bulan);
            }

            rs.close();
            s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencari: "+e.getMessage());
        }

        JFreeChart chart = ChartFactory.createLineChart(
                "Pendapatan Bulanan", "Bulan", "Total Pendapatan",
                dataset);

        ChartPanel panel = new ChartPanel(chart);
        setContentPane(panel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barangBtn;
    private javax.swing.JLabel barangKeluarLabel;
    private javax.swing.JPanel barangKeluarPanel;
    private javax.swing.JLabel barangKeluarValue;
    private javax.swing.JLabel barangMasukLabel;
    private javax.swing.JPanel barangMasukPanel;
    private javax.swing.JLabel barangMasukValue;
    private javax.swing.JLabel dashbaordBtn;
    private javax.swing.JLabel dashbaordLabel5;
    private javax.swing.JLabel dashbaordLabel6;
    private javax.swing.JPanel grafikPendapatan;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel totalBarangLabel;
    private javax.swing.JPanel totalBarangPanel;
    private javax.swing.JLabel totalBarangValue;
    private javax.swing.JLabel totalPendapatanLabel;
    private javax.swing.JPanel totalPendapatanPanel;
    private javax.swing.JLabel totalPendapatanValue;
    private javax.swing.JLabel userBtn;
    // End of variables declaration//GEN-END:variables
}
