/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajemen_toko;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Syahrul Ramadhan
 */
public class Histori extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public Histori() {
        initComponents();
        
        //auto fullscreen
        setExtendedState(Histori.MAXIMIZED_BOTH);
        //bg warna putih
        getContentPane().setBackground(new Color(250, 250, 250));
        
        tampil_tabel_histori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashbaordBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barangBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dashbaordLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dashbaordLabel6 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_histori = new javax.swing.JTable();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideBar.setBackground(new java.awt.Color(237, 255, 249));
        sideBar.setForeground(new java.awt.Color(237, 255, 249));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 142, 110));
        jLabel2.setText("TokoAja.");

        dashbaordBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordBtn.setForeground(new java.awt.Color(123, 122, 120));
        dashbaordBtn.setText("Dashboard");
        dashbaordBtn.setToolTipText("");
        dashbaordBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dashbaordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashbaordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbaordBtnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame.png"))); // NOI18N

        barangBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        barangBtn.setForeground(new java.awt.Color(123, 122, 120));
        barangBtn.setText("Barang");
        barangBtn.setToolTipText("");
        barangBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        barangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangBtnMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/box-1.png"))); // NOI18N

        userBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        userBtn.setForeground(new java.awt.Color(123, 122, 120));
        userBtn.setText("User");
        userBtn.setToolTipText("");
        userBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        userBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBtnMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/Frame-2.png"))); // NOI18N

        historyBtn.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(50, 142, 110));
        historyBtn.setText("Histori");
        historyBtn.setToolTipText("");
        historyBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/transaction-history-stroke-rounded 2.png"))); // NOI18N

        logoutBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/logout.png"))); // NOI18N

        dashbaordLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordLabel5.setText("Icibos");
        dashbaordLabel5.setToolTipText("");
        dashbaordLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons/profile-img.png"))); // NOI18N

        dashbaordLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashbaordLabel6.setForeground(new java.awt.Color(51, 51, 51));
        dashbaordLabel6.setText("Super-admin");
        dashbaordLabel6.setToolTipText("");
        dashbaordLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashbaordBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyBtn))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashbaordLabel5)
                            .addComponent(dashbaordLabel6)))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashbaordBtn)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barangBtn)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userBtn)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historyBtn)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(dashbaordLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashbaordLabel6)))
                .addGap(28, 28, 28)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41))
        );

        tittle.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        tittle.setForeground(new java.awt.Color(50, 142, 110));
        tittle.setText("Histori Aktivitas");

        searchField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        searchField.setSelectionColor(new java.awt.Color(50, 142, 110));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(50, 142, 110));
        searchBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        tabel_histori.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tabel_histori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Histori", "Id User", "Aktivitas", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(tabel_histori);

        resetBtn.setBackground(new java.awt.Color(50, 142, 110));
        resetBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(searchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(resetBtn))
                    .addComponent(tittle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
        String keyword = searchField.getText();
        cariData(keyword);
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String keyword = searchField.getText();
        cariData(keyword);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void dashbaordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbaordBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_dashbaordBtnMouseClicked

    private void barangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new Barang().setVisible(true);
    }//GEN-LAST:event_barangBtnMouseClicked

    private void userBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false); 
        new User().setVisible(true);
    }//GEN-LAST:event_userBtnMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        searchField.setText("");
        tampil_tabel_histori();
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Histori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Histori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Histori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Histori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Histori().setVisible(true);
            }
        });
    }
    
    public void tampil_tabel_histori() {
        // membuat objek model pada tabel
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id Histori");
        tb.addColumn("Id User");
        tb.addColumn("Aktivitas");
        tb.addColumn("Waktu");
        
        try {
            // 1. Query
            String query = "SELECT * FROM history";
            
            // 2. Fungsi Koneksi
            java.sql.Connection Vconn = (Connection)KoneksiDB.configDB();
            
            // 3. Kirim parameter fungsi java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
            // 4. Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            // 5. Looping
            while (r.next()) {
                tb.addRow(new Object[] {
                r.getString(1),r.getString(2),r.getString(3),r.getString(4)
                });
            }
            tabel_histori.setModel(tb);
            
        } catch (Exception e) {
            
        }
        
    }
    
    public void cariData(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Histori");
        model.addColumn("Id User");
        model.addColumn("Aktivitas");
        model.addColumn("Waktu");
        
        try {
            String query = "SELECT * FROM history WHERE id_user LIKE ? OR aktivitas LIKE ? ";
            java.sql.Connection Vconn = (Connection)KoneksiDB.configDB();
            java.sql.PreparedStatement s = Vconn.prepareStatement(query);
            s.setString(1, "%"+keyword+"%");
            s.setString(2, "%"+keyword+"%");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                model.addRow(new Object[] {
                    r.getString("id_history"),
                    r.getString("id_user"),
                    r.getString("aktivitas"),
                    r.getString("waktu"),
                });
            }
            
            tabel_histori.setModel(model);
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencari: "+e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barangBtn;
    private javax.swing.JLabel dashbaordBtn;
    private javax.swing.JLabel dashbaordLabel5;
    private javax.swing.JLabel dashbaordLabel6;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTable tabel_histori;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel userBtn;
    // End of variables declaration//GEN-END:variables
}
